const ADD_USERS = 'ADD_USERS';
const ADD_NEW_USER = 'ADD_NEW_USER';
const UPDATE_USER = 'UPDATE_USER';
const DELETE_USER = 'DELETE_USER';
const ASCENDING_SORT = 'ASCENDING_SORT';
const DESCENDING_SORT = 'DESCENDING_SORT';

export default {
    ADD_USERS,
    ADD_NEW_USER,
    UPDATE_USER,
    DELETE_USER,
    ASCENDING_SORT,
    DESCENDING_SORT
};